# Generated by Django 6.0.5 on 2026-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='home_section',
            field=models.CharField(choices=[('none', 'None'), ('featured', 'Featured'), ('best_seller', 'Best Seller'), ('new_arrival', 'New Arrival')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
