# Generated by Django 6.0.5 on 2026-08-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_home_section_book_show_on_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.BigIntegerField(default=0, help_text='၁၅၀၀'),
        ),
    ]
