# Generated by Django 6.0.5 on 2026-08-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
