# Generated by Django 5.2.14 on 2026-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_emailotpmodel_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('kbzpay', 'KBZPay'), ('wavepay', 'WavePay'), ('uabpay', 'uabPay'), ('ayapay', 'AYAPay')], default='cod', max_length=20),
        ),
    ]
