# Generated by Django 5.2.14 on 2026-09-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_address_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='old_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
