# Generated by Django 5.2.14 on 2026-09-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_book_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='old_price',
        ),
    ]
