# Generated by Django 5.2.14 on 2026-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_pre_order',
            field=models.BooleanField(default=False),
        ),
    ]
