# Generated by Django 5.2.14 on 2026-09-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_book_is_pre_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTPModel',
        ),
    ]
