# Generated by Django 4.2.30 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_emailotpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('lipa-na-mpesa', 'STK push mpesa')], default='cod', max_length=20),
        ),
    ]
